@echo off
cd /d %~dp0/../
if not defined VS_HOME (
    echo 未检测到 VS_HOME 环境变量，
    echo 需要手动输入 Visual Studio 2022 的路径，
    echo 或者设置 VS_HOME 环境变量的值为 Visual Studio 2022 的路径。
    echo （请确保路径下有 VC 文件夹。）
    set /p VS_HOME="请输入 Visual Studio 2022 的路径："
)
if not defined MVN_HOME (
    echo 未检测到 MVN_HOME 环境变量，
    echo 需要手动输入 Maven 3.8.8 的路径，
    echo 或者设置 MVN_HOME 环境变量的值为 Maven 3.8.8 的路径。
    echo （请确保路径下有 bin 文件夹。）
    set /p MVN_HOME="请输入 Maven 3.8.8 的路径："
)
chcp 65001
if defined VS_HOME (
    if defined MVN_HOME (
        cmd.exe /k "%VS_HOME%\VC\Auxiliary\Build\vcvars64.bat & %MVN_HOME%\bin\mvn.cmd gluonfx:build & exit"
    )
)
chcp 936
for /f "tokens=1,* delims=:" %%a in ('findstr /n "<version>" "pom.xml"') do (
    set "startFindVersion=%%b"
    goto :exitFindStart
)
:exitFindStart
for /f "tokens=1,* delims=:" %%a in ('findstr /n "</version>" "pom.xml"') do (
    set "endFindVersion=%%b"
    goto :exitFindEnd
)
:exitFindEnd
call set "version=%%startFindVersion:*<version>=%%"
call set "version=%%version:</version>=%%"
cd pack
echo ; Script generated by the Inno Setup Script Wizard. > windows-10-x64.iss
echo ; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES! >> windows-10-x64.iss
echo. >> windows-10-x64.iss
echo #define MyAppName "文件分割与合并工具" >> windows-10-x64.iss
echo #define MyAppVersion "%version%" >> windows-10-x64.iss
echo #define MyAppPublisher "枫上天游" >> windows-10-x64.iss
echo #define MyAppURL "https://gitlab.com/fstyou/file-split-and-merge-tool" >> windows-10-x64.iss
echo #define MyAppExeName "file-split-and-merge-tool.exe" >> windows-10-x64.iss
echo #define MyAppAssocName MyAppName + "" >> windows-10-x64.iss
echo #define MyAppAssocExt ".myp" >> windows-10-x64.iss
echo #define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt >> windows-10-x64.iss
echo. >> windows-10-x64.iss
echo [Setup] >> windows-10-x64.iss
echo ; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications. >> windows-10-x64.iss
echo ; (To generate a new GUID, click Tools ^| Generate GUID inside the IDE.) >> windows-10-x64.iss
echo AppId={{7BEB6A1A-DBFB-4A8E-A7D6-F5C134B5326A} >> windows-10-x64.iss
echo AppName={#MyAppName} >> windows-10-x64.iss
echo AppVersion={#MyAppVersion} >> windows-10-x64.iss
echo ;AppVerName={#MyAppName} {#MyAppVersion} >> windows-10-x64.iss
echo AppPublisher={#MyAppPublisher} >> windows-10-x64.iss
echo AppPublisherURL={#MyAppURL} >> windows-10-x64.iss
echo AppSupportURL={#MyAppURL} >> windows-10-x64.iss
echo AppUpdatesURL={#MyAppURL} >> windows-10-x64.iss
echo DefaultDirName={autopf}\file-split-and-merge-tool >> windows-10-x64.iss
echo ChangesAssociations=yes >> windows-10-x64.iss
echo DisableProgramGroupPage=yes >> windows-10-x64.iss
echo ; Remove the following line to run in administrative install mode (install for all users.) >> windows-10-x64.iss
echo PrivilegesRequired=lowest >> windows-10-x64.iss
echo PrivilegesRequiredOverridesAllowed=dialog >> windows-10-x64.iss
echo OutputDir=..\target\windows-10-x64\ >> windows-10-x64.iss
echo OutputBaseFilename=mysetup >> windows-10-x64.iss
echo SetupIconFile=..\src\main\resources\icon.ico >> windows-10-x64.iss
echo Compression=lzma >> windows-10-x64.iss
echo SolidCompression=yes >> windows-10-x64.iss
echo WizardStyle=modern >> windows-10-x64.iss
echo. >> windows-10-x64.iss
echo [Languages] >> windows-10-x64.iss
echo Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl" >> windows-10-x64.iss
echo. >> windows-10-x64.iss
echo [Tasks] >> windows-10-x64.iss
echo Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked >> windows-10-x64.iss
echo. >> windows-10-x64.iss
echo [Files] >> windows-10-x64.iss
echo Source: "..\target\gluonfx\x86_64-windows\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion >> windows-10-x64.iss
echo ; NOTE: Don't use "Flags: ignoreversion" on any shared system files >> windows-10-x64.iss
echo. >> windows-10-x64.iss
echo [Registry] >> windows-10-x64.iss
echo Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue >> windows-10-x64.iss
echo Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey >> windows-10-x64.iss
echo Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0" >> windows-10-x64.iss
echo Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%%1""" >> windows-10-x64.iss
echo Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: "" >> windows-10-x64.iss
echo. >> windows-10-x64.iss
echo [Icons] >> windows-10-x64.iss
echo Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}" >> windows-10-x64.iss
echo Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon >> windows-10-x64.iss
echo. >> windows-10-x64.iss
echo [Run] >> windows-10-x64.iss
echo Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent >> windows-10-x64.iss
echo 请用 Inno Setup 6.x （确保已安装中文语言包） 打开 windows-10-x64.iss 文件并运行，生成安装包
echo Inno Setup：hhttps://jrsoftware.org/isdl.php
echo 中文语言包：https://github.com/kira-96/Inno-Setup-Chinese-Simplified-Translation
