; Script generated by the Inno Setup Script Wizard. 
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES! 
 
#define MyAppName "�ļ��ָ���ϲ�����" 
#define MyAppVersion "1.0.0" 
#define MyAppPublisher "��������" 
#define MyAppURL "https://gitlab.com/fstyou/file-split-and-merge-tool" 
#define MyAppExeName "file-split-and-merge-tool.exe" 
#define MyAppAssocName MyAppName + "" 
#define MyAppAssocExt ".myp" 
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt 
 
[Setup] 
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications. 
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.) 
AppId={{7BEB6A1A-DBFB-4A8E-A7D6-F5C134B5326A} 
AppName={#MyAppName} 
AppVersion={#MyAppVersion} 
;AppVerName={#MyAppName} {#MyAppVersion} 
AppPublisher={#MyAppPublisher} 
AppPublisherURL={#MyAppURL} 
AppSupportURL={#MyAppURL} 
AppUpdatesURL={#MyAppURL} 
DefaultDirName={autopf}\file-split-and-merge-tool 
ChangesAssociations=yes 
DisableProgramGroupPage=yes 
; Remove the following line to run in administrative install mode (install for all users.) 
PrivilegesRequired=lowest 
PrivilegesRequiredOverridesAllowed=dialog 
OutputDir=..\target\windows-10-x64\ 
OutputBaseFilename=mysetup 
SetupIconFile=..\src\main\resources\icon.ico 
Compression=lzma 
SolidCompression=yes 
WizardStyle=modern 
 
[Languages] 
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl" 
 
[Tasks] 
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked 
 
[Files] 
Source: "..\target\gluonfx\x86_64-windows\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion 
; NOTE: Don't use "Flags: ignoreversion" on any shared system files 
 
[Registry] 
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue 
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey 
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0" 
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1""" 
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: "" 
 
[Icons] 
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}" 
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon 
 
[Run] 
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent 
